package net.minecraft.server;

public class GenLayerRiverInit extends GenLayer
{
    public GenLayerRiverInit(long par1, GenLayer par3GenLayer)
    {
        super(par1);
        this.a = par3GenLayer;
    }

    /**
     * Returns a list of integer values generated by this layer. These may be interpreted as temperatures, rainfall
     * amounts, or biomeList[] indices based on the particular GenLayer subclass.
     */
    public int[] a(int par1, int par2, int par3, int par4)
    {
        int[] var5 = this.a.a(par1, par2, par3, par4);
        int[] var6 = IntCache.a(par3 * par4);

        for (int var7 = 0; var7 < par4; ++var7)
        {
            for (int var8 = 0; var8 < par3; ++var8)
            {
                this.a((long) (var8 + par1), (long) (var7 + par2));
                var6[var8 + var7 * par3] = var5[var8 + var7 * par3] > 0 ? this.a(2) + 2 : 0;
            }
        }

        return var6;
    }
}
