package net.minecraft.server;

public class GenLayerRiverMix extends GenLayer
{
    private GenLayer b;
    private GenLayer c;

    public GenLayerRiverMix(long par1, GenLayer par3GenLayer, GenLayer par4GenLayer)
    {
        super(par1);
        this.b = par3GenLayer;
        this.c = par4GenLayer;
    }

    /**
     * Initialize layer's local worldGenSeed based on its own baseSeed and the world's global seed (passed in as an
     * argument).
     */
    public void a(long par1)
    {
        this.b.a(par1);
        this.c.a(par1);
        super.a(par1);
    }

    /**
     * Returns a list of integer values generated by this layer. These may be interpreted as temperatures, rainfall
     * amounts, or biomeList[] indices based on the particular GenLayer subclass.
     */
    public int[] a(int par1, int par2, int par3, int par4)
    {
        int[] var5 = this.b.a(par1, par2, par3, par4);
        int[] var6 = this.c.a(par1, par2, par3, par4);
        int[] var7 = IntCache.a(par3 * par4);

        for (int var8 = 0; var8 < par3 * par4; ++var8)
        {
            if (var5[var8] == BiomeBase.OCEAN.id)
            {
                var7[var8] = var5[var8];
            }
            else if (var6[var8] >= 0)
            {
                if (var5[var8] == BiomeBase.ICE_PLAINS.id)
                {
                    var7[var8] = BiomeBase.FROZEN_RIVER.id;
                }
                else if (var5[var8] != BiomeBase.MUSHROOM_ISLAND.id && var5[var8] != BiomeBase.MUSHROOM_SHORE.id)
                {
                    var7[var8] = var6[var8];
                }
                else
                {
                    var7[var8] = BiomeBase.MUSHROOM_SHORE.id;
                }
            }
            else
            {
                var7[var8] = var5[var8];
            }
        }

        return var7;
    }
}
