package net.minecraft.server;

public class GenLayerMushroomShore extends GenLayer
{
    public GenLayerMushroomShore(long par1, GenLayer par3GenLayer)
    {
        super(par1);
        this.a = par3GenLayer;
    }

    /**
     * Returns a list of integer values generated by this layer. These may be interpreted as temperatures, rainfall
     * amounts, or biomeList[] indices based on the particular GenLayer subclass.
     */
    public int[] a(int par1, int par2, int par3, int par4)
    {
        int[] var5 = this.a.a(par1 - 1, par2 - 1, par3 + 2, par4 + 2);
        int[] var6 = IntCache.a(par3 * par4);

        for (int var7 = 0; var7 < par4; ++var7)
        {
            for (int var8 = 0; var8 < par3; ++var8)
            {
                this.a((long) (var8 + par1), (long) (var7 + par2));
                int var9 = var5[var8 + 1 + (var7 + 1) * (par3 + 2)];
                int var10;
                int var11;
                int var12;
                int var13;

                if (var9 == BiomeBase.MUSHROOM_ISLAND.id)
                {
                    var10 = var5[var8 + 1 + (var7 + 1 - 1) * (par3 + 2)];
                    var11 = var5[var8 + 1 + 1 + (var7 + 1) * (par3 + 2)];
                    var12 = var5[var8 + 1 - 1 + (var7 + 1) * (par3 + 2)];
                    var13 = var5[var8 + 1 + (var7 + 1 + 1) * (par3 + 2)];

                    if (var10 != BiomeBase.OCEAN.id && var11 != BiomeBase.OCEAN.id && var12 != BiomeBase.OCEAN.id && var13 != BiomeBase.OCEAN.id)
                    {
                        var6[var8 + var7 * par3] = var9;
                    }
                    else
                    {
                        var6[var8 + var7 * par3] = BiomeBase.MUSHROOM_SHORE.id;
                    }
                }
                else if (var9 != BiomeBase.OCEAN.id && var9 != BiomeBase.RIVER.id && var9 != BiomeBase.SWAMPLAND.id && var9 != BiomeBase.EXTREME_HILLS.id)
                {
                    var10 = var5[var8 + 1 + (var7 + 1 - 1) * (par3 + 2)];
                    var11 = var5[var8 + 1 + 1 + (var7 + 1) * (par3 + 2)];
                    var12 = var5[var8 + 1 - 1 + (var7 + 1) * (par3 + 2)];
                    var13 = var5[var8 + 1 + (var7 + 1 + 1) * (par3 + 2)];

                    if (var10 != BiomeBase.OCEAN.id && var11 != BiomeBase.OCEAN.id && var12 != BiomeBase.OCEAN.id && var13 != BiomeBase.OCEAN.id)
                    {
                        var6[var8 + var7 * par3] = var9;
                    }
                    else
                    {
                        var6[var8 + var7 * par3] = BiomeBase.BEACH.id;
                    }
                }
                else if (var9 == BiomeBase.EXTREME_HILLS.id)
                {
                    var10 = var5[var8 + 1 + (var7 + 1 - 1) * (par3 + 2)];
                    var11 = var5[var8 + 1 + 1 + (var7 + 1) * (par3 + 2)];
                    var12 = var5[var8 + 1 - 1 + (var7 + 1) * (par3 + 2)];
                    var13 = var5[var8 + 1 + (var7 + 1 + 1) * (par3 + 2)];

                    if (var10 == BiomeBase.EXTREME_HILLS.id && var11 == BiomeBase.EXTREME_HILLS.id && var12 == BiomeBase.EXTREME_HILLS.id && var13 == BiomeBase.EXTREME_HILLS.id)
                    {
                        var6[var8 + var7 * par3] = var9;
                    }
                    else
                    {
                        var6[var8 + var7 * par3] = BiomeBase.SMALL_MOUNTAINS.id;
                    }
                }
                else
                {
                    var6[var8 + var7 * par3] = var9;
                }
            }
        }

        return var6;
    }
}
